---
title: "Mechanistic Growth Factors Models and Structural Causal Models"
author: "Robert Osazuwa Ness"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ode2scm)
# Connect Python virtual environment
use_virtualenv('venv', require=TRUE)
```

```{r}
rate_file <- system.file('growth_factor_sheets/growth_factor', 'Values-Rates.csv', package="ode2scm")
rates_raw <- as.list(read.csv(rate_file))
initial_states <-  list(
  EGFR=37,
  IGFR=5,
  SOS_inactive=100,
  SOS_active=0,
  Ras_inactive=100,
  Ras_active=0,
  PI3K_inactive=100,
  PI3K_active=0,
  AKT_inactive=100,
  AKT_active=0,
  Raf_inactive=100,
  Raf_active=0,
  Mek_inactive=100,
  Mek_active=0,
  Erk_inactive=100,
  Erk_active=0
)

```

```{r}
rates <- list(
  SOS_activation_by_EGFR=.01,
  SOS_activation_by_IGFR=.01,
  SOS_deactivation=.5,
  Ras_activation_by_SOS=.01,
  Ras_deactivation=.5,
  PI3K_activation_by_EGFR=.01,
  PI3K_activation_by_IGFR=.01,
  PI3K_activation_by_Ras=.01,
  PI3K_deactivation=.5,
  AKT_activation_by_PI3K=.01,
  AKT_deactivation=.5,
  Raf_activation_by_Ras=.01,
  Raf_deactivation_by_AKT=.01,
  Raf_deactivation_by_phosphotase=.3,
  Mek_activation_by_Raf=.05,
  Mek_deactivation=.5,
  Erk_activation_by_Mek=.05,
  Erk_deactivation=.5
)
```

```{r}
g <- function(a, b) a / (a + b)

ss <- with(rates, {
      EGFR <- 37
      IGFR <- 5
      SOS_active <- 100 * g(
        SOS_activation_by_EGFR * EGFR + SOS_activation_by_IGFR * IGFR, SOS_deactivation 
      )
      Ras_active <- 100 * g(Ras_activation_by_SOS * SOS_active, Ras_deactivation)
      PI3K_active <- 100 * g(
        PI3K_activation_by_EGFR * EGFR +
        PI3K_activation_by_IGFR * IGFR + 
        PI3K_activation_by_Ras * Ras_active,
        PI3K_deactivation
      )
      AKT_active <- 100 * g(AKT_activation_by_PI3K * PI3K_active, AKT_deactivation)
      Raf_active <- 100 * g(
        Raf_activation_by_Ras * Ras_active,
        Raf_deactivation_by_phosphotase + Raf_deactivation_by_AKT * AKT_active
      )
      Mek_active <- 100 * g(Mek_activation_by_Raf * Raf_active, Mek_deactivation)
      Erk_active <- 100 * g(Erk_activation_by_Mek * Mek_active, Erk_deactivation)
      list(
        EGFR=EGFR,
        IGFR=IGFR,
        SOS_active=SOS_active,
        Ras_active=Ras_active,
        PI3K_active=PI3K_active,
        AKT_active=AKT_active,
        Raf_active=Raf_active,
        Mek_active=Mek_active,
        Erk_active=Erk_active
      )
    }
)
```


```{r}
slow_rates <- lapply(rates, `/`, 10)
fast_rates <- lapply(rates, `*`, 10)

times <- seq(0, 100, by = .01)

det_transition_func <- gf_ode(initial_states, slow_rates)
ode_out <- ode_sim(det_transition_func, initial_states, times)
tail(ode_out)[endsWith(names(ode_out), '_active')]

stoc_transition_func <- gf_sde(initial_states, fast_rates)
sde_out <- sde_sim(stoc_transition_func, initial_states, times)

plot(times, ode_out$SOS_active, type='l', col='#2176AE', ylim=c(0, 110))
lines(sde_out$SOS_active, type='l', col='#2176AE', lty=3)
abline(h = ss$SOS_active, col='#2176AE', lty=2)

lines(times, ode_out$Ras_active, type='l', col='#57B8FF')
lines(sde_out$Ras_active, type='l', col='#57B8FF', lty=3)
abline(h = ss$Ras_active, col='#57B8FF', lty=2)

lines(times, ode_out$PI3K_active, type='l', col='#B66D0D')
lines(sde_out$PI3K_active, type='l', col='#B66D0D', lty=3)
abline(h = ss$PI3K_active, col='#B66D0D', lty=2)

lines(times, ode_out$AKT_active, type='l', col='#FBB13C')
lines(sde_out$AKT_active, type='l', col='#FBB13C', lty=3)
abline(h = ss$AKT_active, col='#FBB13C', lty=2)

lines(times, ode_out$Raf_active, type='l', col='#FE6847')
lines(sde_out$Raf_active, type='l', col='#FE6847', lty=3)
abline(h = ss$Raf_active, col='#FE6847', lty=2)

lines(times, ode_out$Mek_active, type='l', col='#BF4F36')
lines(sde_out$Mek_active, type='l', col='#BF4F36', lty=3)
abline(h = ss$Mek_active, col='#BF4F36', lty=2)

lines(times, ode_out$Erk_active, type='l', col='#7F3424')
lines(sde_out$Erk_active, type='l', col='#7F3424', lty=3)
abline(h = ss$Erk_active, col='#7F3424', lty=2)
```


# Counterfactual

The counterfactual intervention on Ras.
 
```{r}
source_python(system.file("python", "gf_scm.py", package = "ode2scm"))

# Reaches equilibrium by 80
time_point <- 80

# Simulate a counterfactual with the ODE. In this case, reduce Ras rate to a 1/3 of original value
# Collect Ras outcome and Erk outcome.
intervention_rates <- rates
intervention_rates$Ras_activation_by_SOS <- rates$Ras_activation_by_SOS / 3
ode_out <- ode_sim(gf_ode(initial_states, intervention_rates), initial_states, times)
n <- which(ode_out$time == time_point)
ras_intervention <- list(Ras=ode_out$Raf_active[n])

seed <- 010203

# Simulate a steady state observation
set.seed(seed)
sde_out_1 <- sde_sim(gf_sde(initial_states, rates), initial_states, times)
observation <- list(
  SOS = sde_out_1$SOS_active[n],
  Ras = sde_out_1$Ras_active[n],
  PI3K = sde_out_1$PI3K_active[n],
  AKT = sde_out_1$AKT_active[n],
  Raf = sde_out_1$Raf_active[n],
  Mek = sde_out_1$Mek_active[n],
  Erk = sde_out_1$Erk_active[n]
)
set.seed(seed)
sde_out_2 <- sde_sim(gf_sde(initial_states, intervention_rates), initial_states, times)
sde_causal_effect <- sde_out_1$Erk_active[n] - sde_out_2$Erk_active[n]

totals <- as.list(rep(100, 7))
names(totals) <- c('SOS', 'Ras', 'PI3K', 'AKT', 'Raf', 'Mek', 'Erk')

ras_intervention <- list(Ras = 30.)
scm_causal_effect_samples <- scm_ras_erk_counterfactual(
  rates,
  totals,
  observation,
  ras_intervention
)
```

```{r}
hist(
  scm_causal_effect_samples,
  main = 'Causal Effect Distribution',
  sub='Red = SDE Causal Effect',
  xlab='Causal Effects',
  freq=F
)
abline(v=sde_causal_effect, col='red')
```
